obj-$(CONFIG_MACH_VISION) += board-vision.o
obj-$(CONFIG_MACH_VISION) += board-vision-keypad.o
obj-$(CONFIG_MACH_VISION) += board-vision-microp.o
obj-$(CONFIG_MACH_VISION) += board-vision-regulator.o
obj-$(CONFIG_MACH_VISION) += display/
