#include "board-tenderloin.h"

static int tenderloin_pins_wifi [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE,
	[BT_RST_N_PIN] = BT_RST_N,
	[BT_POWER_PIN] = BT_POWER,
	[BT_WAKE_PIN] = BT_WAKE,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};

static int tenderloin_pins_3g [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO_3G,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE_3G,
	[BT_RST_N_PIN] = BT_RST_N_3G,
	[BT_POWER_PIN] = BT_POWER_3G,
	[BT_WAKE_PIN] = BT_WAKE_3G,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE_3G,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT_3G,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO_3G,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE_3G,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK_3G,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N_3G,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL_3G,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK_3G,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP_3G,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO_3G,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_3G,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK_3G,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP_3G,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO_3G,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_3G,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO_3G,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO_3G,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};

static int tenderloin_pins_wifi_dvt [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE,
	[BT_RST_N_PIN] = BT_RST_N,
	[BT_POWER_PIN] = BT_POWER,
	[BT_WAKE_PIN] = BT_WAKE,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_DVT,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_DVT,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};

static int tenderloin_pins_3g_evt4[] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO_3G,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE_3G,
	[BT_RST_N_PIN] = BT_RST_N_3G,
	[BT_POWER_PIN] = BT_POWER_3G,
	[BT_WAKE_PIN] = BT_WAKE_3G,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE_3G,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT_3G,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO_3G,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE_3G,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK_3G,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N_3G,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL_3G,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK_3G_DVT,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP_3G,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO_3G,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_3G_DVT,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK_3G,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP_3G,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO_3G,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_3G_DVT,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO_3G,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO_3G,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN,
};


static int tenderloin_pins_3g_dvt [] = {
	[MXT1386_TS_PEN_IRQ] = MXT1386_TS_PEN_IRQ_GPIO_3G,
	[GPIO_CTP_WAKE_PIN] = GPIO_CTP_WAKE_3G,
	[BT_RST_N_PIN] = BT_RST_N_3G,
	[BT_POWER_PIN] = BT_POWER_3G,
	[BT_WAKE_PIN] = BT_WAKE_3G,
	[BT_HOST_WAKE_PIN] = BT_HOST_WAKE_3G,
	[GYRO_INT_PIN] = TENDERLOIN_GYRO_INT_3G,
	[LM8502_LIGHTING_INT_IRQ_PIN] = LM8502_LIGHTING_INT_IRQ_GPIO_3G,
	[MAX8903B_GPIO_USB_CHG_MODE_PIN] = MAX8903B_GPIO_USB_CHG_MODE_3G,
	[MAX8903B_GPIO_DC_OK_PIN] = MAX8903B_GPIO_DC_OK_3G,
	[TENDERLOIN_GPIO_WLAN_RST_N_PIN] = TENDERLOIN_GPIO_WLAN_RST_N_3G,
	[TENDERLOIN_GPIO_HOST_WAKE_WL_PIN] = TENDERLOIN_GPIO_HOST_WAKE_WL_3G,
	[TENDERLOIN_A6_0_TCK_PIN] = TENDERLOIN_A6_0_TCK_3G_DVT,
	[TENDERLOIN_A6_0_WAKEUP_PIN] = TENDERLOIN_A6_0_WAKEUP_3G,
	[TENDERLOIN_A6_0_TDIO_PIN] = TENDERLOIN_A6_0_TDIO_3G,
	[TENDERLOIN_A6_0_MSM_IRQ_PIN] = TENDERLOIN_A6_0_MSM_IRQ_3G_DVT,
	[TENDERLOIN_A6_1_TCK_PIN] = TENDERLOIN_A6_1_TCK_3G,
	[TENDERLOIN_A6_1_WAKEUP_PIN] = TENDERLOIN_A6_1_WAKEUP_3G,
	[TENDERLOIN_A6_1_TDIO_PIN] = TENDERLOIN_A6_1_TDIO_3G,
	[TENDERLOIN_A6_1_MSM_IRQ_PIN] = TENDERLOIN_A6_1_MSM_IRQ_3G_DVT,
	[VOL_UP_GPIO_PIN] = VOL_UP_GPIO_3G,
	[VOL_DN_GPIO_PIN] = VOL_DN_GPIO_3G,
	[TENDERLOIN_GPIO_3G_3V3_EN] = GPIO_3G_3V3_EN_DVT,
};

void __init tenderloin_init_pins(void)
{
	if(boardtype_is_3g()) {
		printk("Choosing tenderloin_pins_3g\n");
		if (board_type >= TOPAZ_3G_DVT) {
			pin_table = &tenderloin_pins_3g_dvt[0];
		} else if (board_type == TOPAZ_3G_EVT4) {
			pin_table = &tenderloin_pins_3g_evt4[0];
		} else {
			pin_table = &tenderloin_pins_3g[0];
		}
	}
	else {
		printk("Choosing tenderloin_pins_wifi\n");
		if (board_type >= TOPAZ_DVT) {
			pin_table = &tenderloin_pins_wifi_dvt[0];
		} else {
			pin_table = &tenderloin_pins_wifi[0];
		}
	}

	tenderloin_fixup_pins();
}
