obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-gpiomux.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-keypad.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-mmc.o
#obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-wifi.o
#obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-rfkill.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-regulator.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-pmic.o
#obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-audio.o
#obj-$(CONFIG_MACH_TENDERLOIN) += display/

