obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-gpiomux.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-keypad.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-regulator.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-pmic.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-ts.o
obj-$(CONFIG_MACH_TENDERLOIN) += board-tenderloin-usb.o
obj-$(CONFIG_MACH_TENDERLOIN) += display/

