obj-$(CONFIG_MACH_OPERAUL) +=  board-operaul-pmic.o board-operaul-storage.o board-operaul-gpiomux.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-gpu.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul.o board-operaul-regulator.o 
#obj-$(CONFIG_MACH_OPERAUL) += board-operaul-audio.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-camera.o
endif
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-keypad.o
obj-$(CONFIG_MACH_OPERAUL) += board-operaul-mmc.o board-operaul-wifi.o
obj-$(CONFIG_MACH_OPERAUL) += display/