obj-$(CONFIG_MACH_M7_UL) += board-m7.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-pmic.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-storage.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-gpiomux.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-keypad.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-wifi.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-audio.o
obj-$(CONFIG_MACH_M7_UL) += board-m7-gpu.o
ifdef CONFIG_MSM_CAMERA
obj-$(CONFIG_MACH_M7_UL) += board-m7-camera.o
endif
ifdef CONFIG_BT
obj-$(CONFIG_MACH_M7_UL) += board-m7-rfkill.o  htc_4335_wl_reg.o
endif
obj-$(CONFIG_MACH_M7_UL) += board-m7-regulator.o
ifdef CONFIG_BT_MSM_SLEEP
obj-$(CONFIG_MACH_M7_UL) += board-m7-bluesleep.o
endif
obj-$(CONFIG_MACH_M7_UL) += display/
