obj-$(CONFIG_MACH_PYRAMID) += board-pyramid.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-gpiomux.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-keypad.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-mmc.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-wifi.o
obj-$(CONFIG_MACH_PYRAMID) += display/

