obj-$(CONFIG_MACH_PYRAMID) += board-pyramid.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-gpiomux.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-keypad.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-mmc.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-storage.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-wifi.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-regulator.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-pmic.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-audio.o
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_PYRAMID) += board-pyramid-camera.o
endif
obj-$(CONFIG_MACH_PYRAMID) += display/

