#
# Makefile for the HTC board
#

# ELITE
obj-$(CONFIG_MACH_ELITE) += elite/

# FIGHTER
obj-$(CONFIG_MACH_FIGHTER) += fighter/

# JET
obj-$(CONFIG_MACH_JET) += jet/

# VILLE
obj-$(CONFIG_MACH_VILLE) += ville/

# TC2
obj-$(CONFIG_MACH_TC2) += tc2/

# OPEARUL
obj-$(CONFIG_MACH_OPERAUL) += operaul/

# M4_UL
obj-$(CONFIG_MACH_M4_UL) += m4ul/