--- drivers/media/video/msm/sensors/Makefile
+++ drivers/media/video/msm/sensors/Makefile
@@ -17,3 +17,4 @@
 obj-$(CONFIG_OV7692) += ov7692_v4l2.o
 obj-$(CONFIG_VX6953) += vx6953.o
 obj-$(CONFIG_OV9724) += ov9724_v4l2.o
+obj-$(CONFIG_S5K3H1GX) += s5k3h1gx_v4l2.o
