obj-$(CONFIG_MACH_SHOOTER) += board-shooter.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-gpiomux.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-keypad.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-mmc.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-storage.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-wifi.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-regulator.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-pmic.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-audio.o
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-rfkill.o
ifeq ($(CONFIG_MSM_CAMERA),y)
obj-$(CONFIG_MACH_SHOOTER) += board-shooter-camera.o
endif
obj-$(CONFIG_MACH_SHOOTER) += display/

